[package]
name = "zxing_cpp2rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0.115" }
flagset = "0.4.4"
num_enum = "0.7.2"
image = { version = "0.24.7", optional = true }


[dev-dependencies]
anyhow = "1.0.79"
image = "0.24.7"
clap = {version = "4.4.13", features = ["derive"]}
cfg-if = "1.0.0"

[build-dependencies]
miette = {version = "5.10.0", features = ["fancy"]}
cxx-build = "1.0.115"

[features]
default = []
image = ["dep:image"]